INSERT INTO `Airport` VALUES (1,'AMS','Amsterdam','The Netherlands','Schiphol'),
                             (2,'DTW','Detroid','USA','Detroid City'),
                             (3,'NRT','Tokyo','Japan','Narita International Airport'),
                             (4,'SYD','Sydney','Australia','Kingsford Smith'),
                             (5,'LAX','Los Angeles','USA','Los Angeles International'),
                             (6,'FRA','Frankfurt','Germany','Frankfurt International Airport'),
                             (7,'ORD','Chicago','USA','Chicago O\'hare International'),
                             (8,'LHR','London','UK','London Heathrow'),
                             (9,'JFK','New York','USA','John F. Kennedy International'),
                             (10,'SIN','Singapore','Singapore','Changi Airport');
